# Render Blueprint – Strapi backend (backend-only repo: no rootDir; use this at repo root)
# After deploy: Render Dashboard → strapi → Environment → add real values for APP_KEYS, API_TOKEN_SALT, ADMIN_JWT_SECRET, TRANSFER_TOKEN_SALT, JWT_SECRET, ENCRYPTION_KEY, STRIPE_SECRET_KEY (from .env).

services:
  - type: web
    name: strapi
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString
      - key: Td8DJ0Y02S1UhnwcFTRYCQ==,hAEgEQkTWKSILf7Lz0IKNQ==,mtq3T3itDZ5WcXmzwj1QoQ==,8ASRPGmGbQ379lr84QkSBg==
        sync: false
      - key: Rbq6o0GiuekQTG+cMhOPUg==
        sync: false
      - key: P1K1vpd7U+/uuFQozYPgPA==
        sync: false
      - key: gMAnTOZeLulgfLfVaO0eZQ==
        sync: false
      - key: R0lU7yMw8D40zQUWcQcjGg==
        sync: false
      - key: JnLMpzrdOBNhmWqgvsWDqQ==
        sync: false
      - key: sk_test_51Suyii4Ch1Ou4n63pYeg8M5Ii5EwW58g1wR2qhA14SzBYoSul7fORdn6o4O1Jp1kSA0XkODZpu9hURvYvOCUPYgZ00K8hdHsGn
        sync: false

databases:
  - name: strapi-db
    plan: free
